apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitleaks-job-runner
  namespace: gitleaks
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "logs"]