apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: vault
  annotations:
    kubernetes.io/description: "Namespace for Vault components"
