apiVersion: v1
kind: Secret
metadata:
  name: agic-secrets
  namespace: kube-system
type: Opaque
stringData:
  subscriptionId: 1c31cbbc-25c4-40cf-8e4e-44be901aa7ef
  resourceGroup: pardeep-rg-0607
  appGwName: applicationgateway
