apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  # RBAC Policy Configuration
  policy.csv: |
    # Default role definition
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, applications, get, argo-cd/*, allow
    p, role:readonly, repositories, get, *, allow
    p, role:readonly, repositories, list, *, allow
    
    # Developer role
    p, role:developer, applications, get, */*, allow
    p, role:developer, applications, create, */*, allow
    p, role:developer, applications, update, */*, allow
    p, role:developer, applications, delete, */*, allow
    p, role:developer, repositories, get, *, allow
    p, role:developer, repositories, list, *, allow
    
    # Admin role
    p, role:admin, *, *, */*, allow
    
    # User mappings
    g, default, role:readonly
    g, okuser, role:developer
  
  # Policy match mode
  policy.matchMode: glob
  
  # OIDC scopes
  scopes: |
    [group, email]
  
  # Optional: User/Group role mappings
  groupRoles: |
    - groupName: admin-group
      roles:
        - role:admin
    - groupName: dev-group
      roles:
        - role:developer
    - groupName: viewer-group
      roles:
        - role:readonly
