apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: azdo-agent-hpa
  namespace: azure-devops-agents
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: azure-devops-agent
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
