apiVersion: batch/v1
kind: Job
metadata:
  name: azdo-agent
  namespace: azdo-agents
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: azdo-agent
        image: mcr.microsoft.com/azure-pipelines/vsts-agent:ubuntu-22.04
        env:
        - name: AZP_URL
          value: https://dev.azure.com/ORG_NAME
        - name: AZP_POOL
          value: kubernetes-pool
        - name: AZP_TOKEN
          valueFrom:
            secretKeyRef:
              name: azdo-agent-secret
              key: AZP_TOKEN
