apiVersion: batch/v1
kind: Job
metadata:
  name: azdo-agent
  namespace: azdo-agents
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: azdo-agent
        # Docker Hub / GitHub Container Registry stable agent image
        image: mcr.microsoft.com/azure-pipelines/azure-pipelines-agent:ubuntu-20.04
        imagePullPolicy: IfNotPresent
        env:
        - name: AZP_URL
          value: https://dev.azure.com/ORG_NAME
        - name: AZP_POOL
          value: kubernetes-pool
        - name: AZP_AGENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: AZP_TOKEN
          valueFrom:
            secretKeyRef:
              name: azdo-agent-secret
              key: AZP_TOKEN
